### PR TITLE
fixing Region unused reference

### PR DESCRIPTION
**Pull request by Ebmtranceboy**

### CODE REVIEW

**Comment by hdgarrood** [comment]
Thanks!

**Comment by rnons** [comment]
Get two errors as of this change
```
Error 1 of 2:

  in module Data.Array.ST
  at bower_components/purescript-arrays/src/Data/Array/ST.purs:34:30 - 34:41 (line 34, column 30 - line 34, column 41)

    Cannot import kind Region from module Control.Monad.ST
    It either does not exist or the module does not export it.


  See https://github.com/purescript/documentation/blob/master/errors/UnknownImport.md for more information,
  or to contribute content related to this error.

Error 2 of 2:

  in module Foreign.Object.ST
  at bower_components/purescript-foreign-object/src/Foreign/Object/ST.purs:14:30 - 14:41 (line 14, column 30 - line 14, column 41)

    Cannot import kind Region from module Control.Monad.ST
    It either does not exist or the module does not export it.


  See https://github.com/purescript/documentation/blob/master/errors/UnknownImport.md for more information,
  or to contribute content related to this error.
```

**Comment by hdgarrood** [comment]
Ah, oops. I guess there must be a compiler bug where it incorrectly marks imports as unused if they are only used in re-exports.

**Comment by hdgarrood** [comment]
Thanks for the report!

**Pull request merged**
