### PR TITLE
Adds uncurried ST functions

### PR DESCRIPTION
**Pull request by mikesol**
**Description of the change**

This PR is a copy-paste of `Effect`'s uncurried functions with an additional `nominal` type parameter.

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by mikesol** [comment]
Apologies for the many failed builds, I was too lazy to do the `pulp` setup on my machine so I just let the CI fail my way to success.

**Comment by JordanMartinez** [comment]
Can you add a changelog update?

**Comment by mikesol** [comment]
Do folks think the nominal parameter should appear first in the ST functions? Currently, it's:

```purescript
STFn10 t a b c d e f g h i j r
```

but it could be instead

```purescript
STFn10 a b c d e f g h i j t r
```

I almost always lead with nominal parameters, but if we did it this way, the order of parameters would follow the type better.

**Comment by JordanMartinez** [comment]
Hm.... If it was at the end but before `r`, then one could define type aliases like:
```purs
--   StFnInt3 t r = StFn Int Int Int t r
type StFnInt3     = StFn Int Int Int
```
vs
```purs
StFnInt3 t = StFn Int Int Int t
```
I guess that's better?

**Comment by mikesol** [comment]
> Hm.... If it was at the end but before `r`, then one could define type aliases like:
> 
> ```purescript
> --   StFnInt3 t r = StFn Int Int Int t r
> type StFnInt3     = StFn Int Int Int
> ```
> 
> vs
> 
> ```purescript
> StFnInt3 t = StFn Int Int Int t
> ```
> 
> I guess that's better?

Changed.

As per the discussion here: https://github.com/purescript/purescript/pull/4386#issuecomment-1237618380, I think this should be merged before we review the compiler change. Let me know if anyone objects.

**Comment by JordanMartinez** [comment]
@garyb Can this get an approval?

**Review by garyb — APPROVED** [review]

**Pull request merged**
